services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  todo-api:
    build: .
    container_name: todo-api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:12345@postgres:5432/todoapp
      JWT_SECRET: mi-super-secreto-jwt-key
      ENABLE_NOTIFICATIONS: "false"
    ports:
      - "3001:3000"  # Puerto 3001 para Docker, 3000 interno
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: